import React, { useMemo } from "react";
import { Modal, Share, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import AppIcon from "../../../../icons/AppIcon";
import { useAppTheme } from "../../../../theme";
import { useLanguage } from "../../../../LanguageContext";
import { formatJobDate } from "../../../Jobs/jobDate";

function formatBudget(v) {
  const raw = String(v || "").trim();
  if (!raw) return "Not set";
  if (/^TZS\b/i.test(raw)) return raw;
  const n = raw.replace(/[^\d.]/g, "");
  return n ? `TZS ${Number(n).toLocaleString("en-US")}` : raw;
}

function categoryLabel(job) {
  return (Array.isArray(job?.categories) && job.categories[0]) || job?.service_type || job?.service || "General";
}

function statusLabel(value) {
  return String(value || "completed").replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

// Rendered as a full-screen Modal instead of a stack route so it can be
// dropped straight into JobWorkspace/WorkspaceProgress without touching
// App.js navigation. It's still a real, dedicated screen — just presented
// modally, matching the pattern the app already uses for full-page sheets
// (e.g. SupportActionSheet, HiringNoticeModal).
export default function JobReceipt({ visible, job, role, onClose }) {
  const { theme } = useAppTheme();
  const { language } = useLanguage();
  const insets = useSafeAreaInsets();
  const styles = useMemo(() => createStyles(theme), [theme]);
  const tx = (en, sw) => (language === "sw" ? sw : en);

  if (!job) return null;

  const contact = job.contact_details;
  const hirer = contact?.hirer;
  const provider = contact?.service_provider;
  const hirerName = hirer?.full_name || hirer?.username || (role === "hirer" ? tx("You", "Wewe") : tx("Not available", "Haipatikani"));
  const providerName = provider?.full_name || provider?.username || (role === "provider" ? tx("You", "Wewe") : tx("Not available", "Haipatikani"));
  const code = job.job_code || job.code || "JOB";
  const budget = formatBudget(job.assigned_budget || job.budget);
  const postedAt = formatJobDate(job.created_at) || tx("Not recorded", "Haijarekodiwa");
  const startedAt = formatJobDate(job.started_at) || tx("Not recorded", "Haijarekodiwa");
  const completedAt = formatJobDate(job.completed_at) || tx("Not recorded", "Haijarekodiwa");
  const status = statusLabel(job.status);

  const shareReceipt = async () => {
    const lines = [
      "e-kazi — Job Receipt",
      "─────────────────────",
      `Job code: ${code}`,
      `Title: ${job.title || "Untitled job"}`,
      `Category: ${categoryLabel(job)}`,
      `Hirer: ${hirerName}`,
      `Provider: ${providerName}`,
      `Agreed amount: ${budget}`,
      `Posted: ${postedAt}`,
      `Started: ${startedAt}`,
      `Completed: ${completedAt}`,
      `Status: ${status}`,
      "─────────────────────",
      "Generated by e-kazi",
    ];
    try {
      await Share.share({
        title: `e-kazi Receipt — ${code}`,
        message: lines.join("\n"),
      });
    } catch (err) {
      console.log("share receipt error:", err?.message);
    }
  };

  return (
    <Modal visible={!!visible} animationType="slide" onRequestClose={onClose}>
      <View style={[styles.safe, { paddingTop: insets.top }]}>
        <View style={styles.header}>
          <TouchableOpacity onPress={onClose} style={styles.backButton} hitSlop={8}>
            <AppIcon name="close" size={20} color={theme.colors.text} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>{tx("Job Receipt", "Risiti ya Kazi")}</Text>
          <View style={styles.headerSpacer} />
        </View>

        <View style={styles.content}>
          {/* ── Receipt card ── */}
          <View style={styles.card}>
            <View style={styles.cardTop}>
              <View style={styles.stampWrap}>
                <AppIcon name="award" size={30} color={theme.colors.success} />
              </View>
              <Text style={styles.completedLabel}>{tx("JOB COMPLETED", "KAZI IMEKAMILIKA")}</Text>
              <Text style={styles.jobTitle} numberOfLines={2}>{job.title || tx("Untitled job", "Kazi bila kichwa")}</Text>
              <View style={styles.codePill}>
                <Text style={styles.codeText}>{code}</Text>
              </View>
            </View>

            <View style={styles.divider} />

            <ReceiptRow label={tx("Category", "Aina")} value={categoryLabel(job)} />
            <ReceiptRow label={tx("Hirer", "Mwajiri")} value={hirerName} />
            <ReceiptRow label={tx("Provider", "Mtoa Huduma")} value={providerName} />
            <ReceiptRow label={tx("Posted", "Ilichapishwa")} value={postedAt} />
            <ReceiptRow label={tx("Started", "Ilianza")} value={startedAt} />
            <ReceiptRow label={tx("Completed", "Imekamilika")} value={completedAt} />
            <ReceiptRow label={tx("Final Status", "Hali ya Mwisho")} value={status} />

            <View style={styles.divider} />

            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>{tx("Agreed Amount", "Kiasi Kilichokubaliwa")}</Text>
              <Text style={styles.totalValue}>{budget}</Text>
            </View>

            <View style={styles.footerNote}>
              <Text style={styles.footerNoteText}>
                {tx("This receipt was generated automatically by e-kazi from the job's recorded pipeline data.", "Risiti hii imetengenezwa kiotomatiki na e-kazi kutoka kwenye data ya hatua za kazi zilizorekodiwa.")}
              </Text>
            </View>
          </View>

          <TouchableOpacity style={styles.shareButton} onPress={shareReceipt} activeOpacity={0.85}>
            <AppIcon name="share2" size={17} color={theme.colors.onPrimary} />
            <Text style={styles.shareButtonText}>{tx("Share Receipt", "Shiriki Risiti")}</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );
}

function ReceiptRow({ label, value }) {
  const { theme } = useAppTheme();
  const styles = useMemo(() => createStyles(theme), [theme]);
  return (
    <View style={styles.row}>
      <Text style={styles.rowLabel}>{label}</Text>
      <Text style={styles.rowValue} numberOfLines={1}>{value}</Text>
    </View>
  );
}

const createStyles = (theme) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.colors.bg },
    header: {
      minHeight: 48,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    backButton: { width: 38, height: 38, alignItems: "center", justifyContent: "center" },
    headerSpacer: { width: 38 },
    headerTitle: { flex: 1, textAlign: "center", color: theme.colors.text, fontSize: 17, fontWeight: "900" },
    content: { flex: 1, padding: 16 },

    card: {
      backgroundColor: theme.colors.surface,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 20,
      shadowColor: "#000",
      shadowOpacity: 0.06,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    },
    cardTop: { alignItems: "center", gap: 6, paddingBottom: 4 },
    stampWrap: {
      width: 56, height: 56, borderRadius: 28,
      alignItems: "center", justifyContent: "center",
      backgroundColor: theme.colors.successSoft,
      marginBottom: 2,
    },
    completedLabel: { color: theme.colors.success, fontSize: 11, fontWeight: "900", letterSpacing: 1.2 },
    jobTitle: { color: theme.colors.text, fontSize: 19, fontWeight: "900", textAlign: "center", marginTop: 2 },
    codePill: { marginTop: 6, backgroundColor: theme.colors.primarySoft, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 4 },
    codeText: { color: theme.colors.primaryStrong, fontSize: 12, fontWeight: "900", letterSpacing: 0.4 },

    divider: { height: 1, backgroundColor: theme.colors.border, marginVertical: 14 },

    row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 6, gap: 10 },
    rowLabel: { color: theme.colors.textMuted, fontSize: 12.5, fontWeight: "700" },
    rowValue: { flex: 1, textAlign: "right", color: theme.colors.text, fontSize: 13, fontWeight: "800" },

    totalRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 2 },
    totalLabel: { color: theme.colors.text, fontSize: 14, fontWeight: "900" },
    totalValue: { color: theme.colors.primaryStrong, fontSize: 20, fontWeight: "900" },

    footerNote: { marginTop: 18, paddingTop: 14, borderTopWidth: 1, borderTopColor: theme.colors.border },
    footerNoteText: { color: theme.colors.textMuted, fontSize: 10.5, lineHeight: 15, textAlign: "center", fontStyle: "italic" },

    shareButton: {
      flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
      minHeight: 50, borderRadius: 14, marginTop: 18,
      backgroundColor: theme.colors.primary,
      shadowColor: theme.colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 10, elevation: 3,
    },
    shareButtonText: { color: theme.colors.onPrimary, fontSize: 14, fontWeight: "900" },
  });
